### PR TITLE
fix: use the globally installed version in the shell script

### LINKED ISSUE #83: hitting tab can be faster!
no delay after this:
`About to call: eval node /Users/amir/.nvm/versions/node/v22.13.0/bin/tab pnpm complete -- '' ''
`

### PR DESCRIPTION
**Pull request by AmirSa12**
resolves #83

### CODE REVIEW

File: bin/cli.ts [hunk 1]
```diff
@@ -64,9 +64,13 @@ async function main() {
...
   const name = packageManager;
-  const executable = process.env.npm_config_user_agent
-    ? `npx --yes @bomb.sh/tab ${packageManager}`
-    : `node ${process.argv[1]} ${packageManager}`;
+
+  const isLocalDev = process.argv[1].endsWith('dist/bin/cli.js');
+
+  const executable = isLocalDev
+    ? `node ${process.argv[1]} ${packageManager}`
+    : `tab ${packageManager}`;
```
Comment (Aslemammad) [inline bin/cli.ts]: i think we should still use npx/pnpx/... even if it's installed globally
